# Generated by Django 6.0.7 on 2026-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_completed', 'Buyurtma tugallandi'), ('order_cancelled', 'Buyurtma bekor qilindi'), ('order_pending', 'Buyurtma kutilmoqda'), ('order_processing', 'Buyurtma bajarilmoqda'), ('payment_received', "To'lov qabul qilindi")], max_length=100)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('template_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notifications',
            },
        ),
    ]
