# Generated by Django 6.0.7 on 2026-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 86 Diamond', max_length=200)),
                ('amount_label', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction_text', models.TextField(blank=True, help_text="Mijozga ko'rinadigan yo'riqnoma", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Masalan: game_id, server_id', max_length=100)),
                ('field_label', models.CharField(help_text='Masalan: Game ID', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Matn'), ('number', 'Raqam'), ('select', 'Tanlov')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('validation_regex', models.CharField(blank=True, max_length=500, null=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'service_fields',
                'ordering': ['order_index'],
            },
        ),
    ]
