# Generated by Django 6.0.7 on 2026-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefield',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Select turi uchun variantlar (masalan: ["1 oy", "3 oy", "6 oy"])'),
        ),
    ]
