# Generated by Django 6.0.7 on 2026-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
