# Generated by Django 6.0.7 on 2026-07-31 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramWebAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('launch_source', models.CharField(default='telegram_webapp', max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram WebApp Session',
                'verbose_name_plural': 'Telegram WebApp Sessions',
                'db_table': 'telegram_webapp_sessions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
