# Generated by Django 6.0.7 on 2026-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramwebappsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('telegram_id', models.CharField(db_index=True, max_length=100)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram Login Code',
                'verbose_name_plural': 'Telegram Login Codes',
                'db_table': 'telegram_login_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
