# Generated by Django 6.0.7 on 2026-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramlogincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlogincode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
