# Generated by Django 6.0.7 on 2026-08-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramlogincode_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramlogincode',
            name='attempts',
        ),
    ]
