# Generated by Django 6.0.7 on 2026-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_telegramlogincode_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlogincode',
            name='code',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
