# Generated by Django 6.0.7 on 2026-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_hash_legacy_login_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fragment_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_telegram_premium',
            field=models.BooleanField(default=False),
        ),
    ]
