# Generated by Django 6.0.7 on 2026-08-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_fragment_synced_at_user_is_telegram_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramwebappsession',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
