# Generated by Django 6.0.7 on 2026-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_telegramwebappsession_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramwebappsession',
            name='diag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
