# Generated by Django 5.2.17 on 2026-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_telegramwebappsession_location_user_geo_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
