# Generated by Django 5.2.17 on 2026-08-11 07:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_last_ip_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.PositiveIntegerField()),
                ('reward_label', models.CharField(default='Telegram Premium 1 oy', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('45000'), max_digits=15)),
                ('status', models.CharField(choices=[('granted', 'Berildi'), ('failed', 'Muvaffaqiyatsiz')], default='granted', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_rewards',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'milestone')},
            },
        ),
    ]
