# Generated by Django 5.2.17 on 2026-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo_source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
