# Generated by Django 5.1 on 2026-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_avatar_url'),
        ('users', '0016_premiumactivationcode'),
    ]

    operations = [
    ]
