"""
Referral System Views for DONZO.

The User model already has:
- referral_code (unique, autogenerated on registration)
- referred_by (FK to self)
- cashback_balance (earned from referrals)

Money movement lives in referral_service.py (credit on payment / reversal
on refund). These views READ the ledger and expose it:
- GET /api/v1/referrals/ — list user's referrals (+ real earned cashback)
- GET /api/v1/referrals/stats/ — referral earnings stats
- POST /api/v1/referrals/claim-bonus/ — claim cashback referral bonuses
- POST /api/v1/referrals/apply-code/ — link a user to a referrer
"""
import logging
from decimal import Decimal

from django.db import transaction
from django.utils import timezone
from datetime import timedelta

from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes

from .models import User
from .serializers import UserSerializer

logger = logging.getLogger(__name__)

REFERRAL_BONUS_PERCENT = Decimal('5')  # 5% cashback to referrer
REFERRAL_BONUS_FLAT = Decimal('0')      # No flat bonus (percentage only)
MIN_ORDER_FOR_REFERRAL = Decimal('10000')  # Min 10,000 so'm order to qualify


def _cashback_txs(user):
    """Completed cashback BalanceTransactions for a user (the real ledger)."""
    from apps.payments.models import BalanceTransaction
    return BalanceTransaction.objects.filter(
        user=user, tx_type='cashback', status='completed'
    )


def _sum_cashback_txs(qs):
    from django.db.models import Sum
    return qs.aggregate(total=Sum('amount'))['total'] or Decimal('0')


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def my_referrals(request):
    """
    GET /api/v1/referrals/

    Returns the list of users who registered using this user's referral code.
    Includes their registration date, total spent and the REAL cashback this
    user actually earned from them (from the balance ledger — 0 if the
    referral never paid for an order).
    """
    user = request.user

    referrals = User.objects.filter(
        referred_by=user
    ).values(
        'id', 'username', 'created_at', 'balance', 'cashback_balance'
    ).order_by('-created_at')

    # Calculate total spent for each referral from orders
    from apps.orders.models import Order
    from django.db.models import Sum

    results = []
    for ref in referrals:
        total_spent = Order.objects.filter(
            customer_id=ref['id'],
            payment_status='paid'
        ).aggregate(total=Sum('total_price'))['total'] or Decimal('0')

        # Real earned cashback = sum of 'cashback' ledger entries on THIS
        # user's account whose provider_transaction_id references one of this
        # referred user's paid orders (REF:{order_number}).
        ref_order_numbers = list(
            Order.objects.filter(
                customer_id=ref['id'], payment_status='paid'
            ).values_list('order_number', flat=True)
        )
        earned = Decimal('0')
        if ref_order_numbers:
            prefixes = [f"REF:{n}" for n in ref_order_numbers]
            from django.db.models import Q
            earned = _sum_cashback_txs(
                _cashback_txs(user).filter(
                    Q(provider_transaction_id__in=prefixes)
                    | Q(description__contains=f"@{ref['username']}")
                )
            )

        results.append({
            'id': ref['id'],
            'username': ref['username'],
            'registered_at': ref['created_at'].isoformat(),
            'total_spent': float(total_spent),
            'earned_cashback': float(earned),
        })

    return Response({
        'count': len(results),
        'results': results,
    })


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def referral_stats(request):
    """
    GET /api/v1/referrals/stats/

    Returns referral statistics for the current user:
    - referral_code: user's own referral code
    - total_referrals: number of referred users
    - total_cashback_earned: total cashback ACTUALLY earned (ledger)
    - available_cashback: cashback that hasn't been claimed yet
    - referral_link: full referral URL (points at the home page with ?ref=)
    """
    user = request.user

    # ── Milestone gift backfill ──
    # Existing users who already crossed a milestone get their gift the next
    # time they open the referral page (idempotent — never double-grants).
    from .referral_service import grant_referral_milestone_rewards
    grant_referral_milestone_rewards(user)

    total_referrals = User.objects.filter(referred_by=user).count()

    # Real earned cashback — from the balance ledger, not a hypothetical sum.
    total_cashback_earned = _sum_cashback_txs(_cashback_txs(user))

    # Friends' total paid spend
    from apps.orders.models import Order
    from django.db.models import Sum
    referred_ids = list(User.objects.filter(referred_by=user).values_list('id', flat=True))
    total_referred_spent = Order.objects.filter(
        customer_id__in=referred_ids, payment_status='paid'
    ).aggregate(total=Sum('total_price'))['total'] or Decimal('0')

    site_url = request.build_absolute_uri('/').rstrip('/')

    # ── Milestone gift info (30 friends → 1 month Telegram Premium) ──
    from .models import ReferralReward
    rewards_granted = ReferralReward.objects.filter(
        referrer=user, status='granted'
    ).count()
    next_milestone = ReferralReward.MILESTONE_EVERY * (rewards_granted + 1)
    milestone_progress = max(0, total_referrals - ReferralReward.MILESTONE_EVERY * rewards_granted)

    return Response({
        'referral_code': user.referral_code,
        # Login was removed — the link points at the home page; the auto-login
        # + ?ref= attribution flow applies the code after the user is in.
        'referral_link': f"{site_url}/?ref={user.referral_code}",
        'total_referrals': total_referrals,
        'total_cashback_earned': float(total_cashback_earned),
        'available_cashback': float(user.cashback_balance or 0),
        'current_balance': float(user.balance or 0),
        'bonus_percent': float(REFERRAL_BONUS_PERCENT),
        'min_order_for_referral': float(MIN_ORDER_FOR_REFERRAL),
        'total_referred_spent': float(total_referred_spent),
        # Milestone gift (30 friends → 1 month Telegram Premium)
        'milestone_every': ReferralReward.MILESTONE_EVERY,
        'milestone_progress': milestone_progress,
        'next_milestone': next_milestone,
        'rewards_granted': rewards_granted,
        'reward_label': ReferralReward.REWARD_LABEL_1M_PREMIUM,
    })


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def claim_referral_bonus(request):
    """
    POST /api/v1/referrals/claim-bonus/

    Transfer available cashback balance to main balance.
    Requires minimum cashback amount. Writes a 'cashback_claim'
    BalanceTransaction so the movement is fully auditable.
    """
    user = request.user
    cashback = user.cashback_balance or Decimal('0')

    if cashback < Decimal('1000'):
        return Response(
            {'detail': f"Minimal cashback summasi 1,000 so'm. Sizda: {float(cashback):,.0f} so'm"},
            status=status.HTTP_400_BAD_REQUEST
        )

    from apps.payments.models import BalanceTransaction
    from apps.audit_log.models import AuditLog

    with transaction.atomic():
        user = User.objects.select_for_update().get(pk=user.pk)
        cashback = user.cashback_balance or Decimal('0')
        if cashback < Decimal('1000'):
            return Response(
                {'detail': f"Minimal cashback summasi 1,000 so'm. Sizda: {float(cashback):,.0f} so'm"},
                status=status.HTTP_400_BAD_REQUEST
            )

        balance_before = user.balance or Decimal('0')
        user.balance = balance_before + cashback
        user.cashback_balance = Decimal('0')
        user.save(update_fields=['balance', 'cashback_balance'])

        BalanceTransaction.objects.create(
            user=user,
            tx_type='cashback_claim',
            amount=cashback,
            balance_before=balance_before,
            balance_after=user.balance,
            status='completed',
            provider='referral',
            description=f"Referal cashback balansga o'tkazildi: {cashback} so'm",
        )

        AuditLog.objects.create(
            user=user,
            action='referral_cashback_claim',
            target_type='User',
            target_id=user.id,
            description=f"@{user.username} {cashback} so'm cashbackni balansga o'tkazdi",
        )

    logger.info(f"[Referral] User {user.username} claimed {cashback} so'm cashback")

    return Response({
        'detail': f"{float(cashback):,.0f} so'm cashback balansga o'tkazildi",
        'new_balance': float(user.balance),
        'new_cashback': 0,
    })


@api_view(['POST'])
@permission_classes([permissions.AllowAny])
def apply_referral_code(request):
    """
    POST /api/v1/referrals/apply-code/

    Apply a referral code during registration (or after).
    Body: { "referral_code": "XXXXX" }

    This can be called after registration to link a user to their referrer.
    Guards: no self-referral, no double-link, referrer must exist & be active.
    """
    from rest_framework import serializers

    class RefCodeSerializer(serializers.Serializer):
        referral_code = serializers.CharField(max_length=50)

    serializer = RefCodeSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)

    code = serializer.validated_data['referral_code'].strip().upper()

    if not request.user.is_authenticated:
        return Response(
            {'detail': 'Foydalanuvchi tizimga kirmagan'},
            status=status.HTTP_401_UNAUTHORIZED
        )

    user = request.user

    # Can't refer yourself
    if user.referral_code == code:
        return Response(
            {'detail': "O'zingizni referral kodingizni ishlata olmaysiz"},
            status=status.HTTP_400_BAD_REQUEST
        )

    # Already has a referrer
    if user.referred_by:
        return Response(
            {'detail': 'Siz allaqachon referal tizimiga ulangansiz'},
            status=status.HTTP_400_BAD_REQUEST
        )

    try:
        referrer = User.objects.get(referral_code=code, is_active=True)
    except User.DoesNotExist:
        return Response(
            {'detail': 'Referral kod topilmadi'},
            status=status.HTTP_404_NOT_FOUND
        )

    # Staff members cannot be "referred" — they are not customers.
    STAFF_ROLES = ['admin', 'super_admin', 'senior_operator', 'operator', 'support']
    if referrer.role in STAFF_ROLES or user.role in STAFF_ROLES:
        return Response(
            {'detail': 'Xodim hisoblari referal tizimiga ulanmaydi'},
            status=status.HTTP_400_BAD_REQUEST
        )

    user.referred_by = referrer
    user.save(update_fields=['referred_by'])

    from apps.audit_log.models import AuditLog
    AuditLog.objects.create(
        user=user,
        action='referral_linked',
        target_type='User',
        target_id=user.id,
        description=f"@{user.username} @{referrer.username} tomonidan taklif qilindi",
    )

    # ── Milestone gift check ──
    # If this link pushed the referrer over a milestone (30/60/90 ...), the
    # gift (1 month Telegram Premium) is granted right here.
    from .referral_service import grant_referral_milestone_rewards
    grant_referral_milestone_rewards(referrer)

    logger.info(f"[Referral] User {user.username} linked to referrer {referrer.username}")

    return Response({
        'detail': f"Siz @{referrer.username} tomonidan taklif qilingansiz",
        'referrer_username': referrer.username,
    })


# ─── Admin Referral Management ───


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def admin_referral_stats(request):
    """
    GET /api/v1/admin/referrals/stats/

    Admin view: overall referral system statistics.
    Only accessible by admin/super_admin roles.
    """
    from apps.users.permissions import IsAdmin
    if not IsAdmin().has_permission(request, None):
        return Response({'detail': 'Ruxsat yo\'q'}, status=status.HTTP_403_FORBIDDEN)

    total_users_with_referrer = User.objects.filter(referred_by__isnull=False).count()
    total_users_with_code = User.objects.exclude(referral_code__isnull=True).count()
    total_referrers = User.objects.filter(
        id__in=User.objects.filter(referred_by__isnull=False).values_list('referred_by', flat=True)
    ).count()

    # Top referrers
    from django.db.models import Count
    top_referrers = (
        User.objects.filter(referred_by__isnull=False)
        .values('referred_by__username', 'referred_by__id')
        .annotate(count=Count('id'))
        .order_by('-count')[:10]
    )

    from apps.orders.models import Order
    from django.db.models import Sum

    total_referral_revenue = Order.objects.filter(
        customer__referred_by__isnull=False,
        payment_status='paid'
    ).aggregate(total=Sum('total_price'))['total'] or Decimal('0')

    # ACTUAL cashback paid out from the ledger (not hypothetical).
    from apps.payments.models import BalanceTransaction
    actual_cashback = BalanceTransaction.objects.filter(
        tx_type='cashback', status='completed'
    ).aggregate(total=Sum('amount'))['total'] or Decimal('0')

    return Response({
        'total_users_with_referrer': total_users_with_referrer,
        'total_users_with_code': total_users_with_code,
        'total_referrers': total_referrers,
        'total_referral_revenue': float(total_referral_revenue),
        'estimated_cashback_paid': float(actual_cashback),
        'top_referrers': [
            {
                'username': r['referred_by__username'],
                'id': r['referred_by__id'],
                'referrals_count': r['count'],
            }
            for r in top_referrers
        ],
    })
