# Generated by Django 5.2.17 on 2026-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('ads_count', models.PositiveIntegerField(default=0)),
                ('joins_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marketing daily stat',
                'verbose_name_plural': 'Marketing daily stats',
                'db_table': 'marketing_daily_stats',
            },
        ),
        migrations.CreateModel(
            name='MarketingGroupStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('chat_title', models.CharField(blank=True, default='', max_length=255)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('ads_count', models.PositiveIntegerField(default=0)),
                ('joins_count', models.PositiveIntegerField(default=0)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing group stat',
                'verbose_name_plural': 'Marketing group stats',
                'db_table': 'marketing_group_stats',
            },
        ),
    ]
