# Generated by Django 5.2.17 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_marketing_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('last_roast_at', models.DateTimeField(blank=True, null=True)),
                ('roast_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing group member',
                'verbose_name_plural': 'Marketing group members',
                'db_table': 'marketing_group_members',
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'username'), name='uniq_member_chat_username')],
            },
        ),
    ]
