# Generated by Django 6.0.7 on 2026-08-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardpay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rule_score', models.PositiveSmallIntegerField(default=0)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='LOW', max_length=10)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_available', models.BooleanField(default=False)),
                ('ai_error', models.CharField(blank=True, default='', max_length=200)),
                ('shadow_mode', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('detected_patterns', models.JSONField(blank=True, default=list)),
                ('rule_triggers', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('APPROVED', 'Tasdiqlandi'), ('HOLD', 'Ushlab turildi'), ('MANUAL_REVIEW', "Qo'lda tekshirish"), ('BLOCKED', 'Bloklandi'), ('REJECTED', 'Rad etildi'), ('ANALYZING', 'Tahlil qilinmoqda'), ('AI_UNAVAILABLE', 'AI mavjud emas')], default='ANALYZING', max_length=20)),
                ('shadow_decision', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='cardpay.cardpaymentmessage')),
                ('topup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='cardpay.cardtopuprequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_risk_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('points', models.SmallIntegerField(default=0)),
                ('severity', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='LOW', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='security.paymentriskassessment')),
            ],
            options={
                'db_table': 'risk_events',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='HIGH', max_length=10)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('ACKED', 'Qabul qilingan'), ('INVESTIGATING', 'Tekshirilmoqda'), ('RESOLVED', 'Hal qilindi'), ('FALSE_POSITIVE', "Yolg'on signal"), ('CONFIRMED_FRAUD', 'Firibgarlik tasdiqlandi')], default='OPEN', max_length=20)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rule_triggers', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('related_game_ids', models.JSONField(blank=True, default=list)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acked_incidents', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security.paymentriskassessment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('topup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='cardpay.cardtopuprequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('INVESTIGATING', 'Tekshirilmoqda'), ('WAITING', 'Kutilmoqda'), ('CLEARED', 'Tozalangan'), ('CONFIRMED_FRAUD', 'Firibgarlik tasdiqlandi'), ('CLOSED', 'Yopilgan')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=10)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cases', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='security_cases_users', to=settings.AUTH_USER_MODEL)),
                ('incidents', models.ManyToManyField(blank=True, related_name='cases', to='security.securityincident')),
            ],
            options={
                'db_table': 'security_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='HIGH', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='HIGH', max_length=10)),
                ('recipient', models.CharField(blank=True, default='', max_length=200)),
                ('message_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SENT', 'Yuborilgan'), ('ESCALATED', 'Kuchaytirilgan'), ('ACKED', 'Qabul qilingan')], default='SENT', max_length=20)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('acked_by', models.CharField(blank=True, default='', max_length=100)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security.securityincident')),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('CRITICAL', 'Kritik')], default='LOW', max_length=10)),
                ('admin_flag', models.CharField(choices=[('trusted', 'Ishonchli'), ('watch', 'Kuzatuvda'), ('blocked', 'Bloklangan'), ('normal', 'Oddiy')], default='normal', max_length=10)),
                ('lifetime_volume', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('volume_7d', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('suspicious_count', models.PositiveIntegerField(default=0)),
                ('hold_count', models.PositiveIntegerField(default=0)),
                ('game_ids', models.JSONField(blank=True, default=list)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_risk_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'severity'], name='security_in_status_f14b6b_idx'),
        ),
    ]
