# Generated by Django 6.0.7 on 2026-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('field_values', models.JSONField(blank=True, default=dict)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_telegram', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Bajarilmoqda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('paid', "To'langan"), ('refunded', 'Qaytarilgan')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
