# Generated by Django 6.0.7 on 2026-08-06 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_balancetransaction_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100)),
                ('message_id', models.BigIntegerField()),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_amounts', models.CharField(blank=True, default='', max_length=200)),
                ('is_outgoing', models.BooleanField(default=False, help_text='Chiqim/списание xabari')),
                ('sender_id', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(blank=True, default='', help_text='matched / no_match / suspicious / ignored', max_length=30)),
            ],
            options={
                'db_table': 'card_payment_messages',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'message_id'), name='uniq_card_msg_chat_message')],
            },
        ),
        migrations.CreateModel(
            name='CardTopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unique_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=15)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan")], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_requests', to='payments.balancetransaction')),
                ('matched_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='cardpay.cardpaymentmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_topup_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_suspicious', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_payments', to='cardpay.cardpaymentmessage')),
                ('topup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_payments', to='cardpay.cardtopuprequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suspicious_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardtopuprequest',
            index=models.Index(fields=['status', 'unique_amount'], name='card_topup__status_64b6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtopuprequest',
            index=models.Index(fields=['status', 'expires_at'], name='card_topup__status_3226cf_idx'),
        ),
    ]
