# Generated by Django 5.2.17 on 2026-08-11 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('card_holder', models.CharField(blank=True, default='', max_length=120)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False, help_text="Ayni paytda mijozlarga ko'rsatiladigan karta")),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text="Ushbu kartaga kelishi mumkin bo'lgan maksimal summa (0 = cheksiz)", max_digits=15)),
                ('max_transfers', models.PositiveIntegerField(default=0, help_text="Maksimal o'tkazmalar soni (0 = cheksiz)")),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Joriy davrda kelgan summa', max_digits=15)),
                ('transfers_count', models.PositiveIntegerField(default=0)),
                ('auto_reset_daily', models.BooleanField(default=True, help_text='Har kuni yarim tunda hisoblagichlarni tiklash')),
                ('period_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_switch_at', models.DateTimeField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_cards',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
