# Generated by Django 5.1 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpay', '0002_paymentcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Barqaror raqam (2..N). Sessiya fayli nomida ishlatiladi.', unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('session_b64', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('authorized', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('tg_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('restarts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_client_accounts',
                'ordering': ['slot'],
            },
        ),
    ]
