# Generated by Django 6.0.7 on 2026-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('paynet', 'Paynet'), ('fragment', 'Fragment (TON)'), ('balance', 'Balans')], max_length=50),
        ),
    ]
