# Generated by Django 5.2.17 on 2026-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_balancetransaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='tx_type',
            field=models.CharField(choices=[('topup', "To'ldirish"), ('purchase', 'Xarid'), ('cashback', 'Cashback'), ('cashback_claim', "Cashback balansga o'tkazildi"), ('admin', 'Admin tuzatmasi'), ('refund', 'Qaytarildi')], max_length=20),
        ),
    ]
