# Generated by Django 5.2.17 on 2026-08-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_balancetransaction_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='tx_type',
            field=models.CharField(choices=[('topup', "To'ldirish"), ('purchase', 'Xarid'), ('cashback', 'Cashback'), ('cashback_claim', "Cashback balansga o'tkazildi"), ('referral_gift', "Referal sovg'a"), ('admin', 'Admin tuzatmasi'), ('refund', 'Qaytarildi')], max_length=20),
        ),
    ]
